<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\AuraCinema.Domain\AuraCinema.Domain.csproj" />
    <ProjectReference Include="..\AuraCinema.Infrastructure\AuraCinema.Infrastructure.csproj" />
    <ProjectReference Include="..\AuraCinema.Services\AuraCinema.Services.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.15" />
    <PackageReference Include="payOS" Version="1.0.6" />
    <PackageReference Include="Serilog.AspNetCore" Version="8.0.3" />
    <PackageReference Include="Serilog.Sinks.File" Version="5.0.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>6536c956-81aa-417d-97c7-8f0face23608</UserSecretsId>
  </PropertyGroup>

</Project>
